# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "CI環境でのコンパイルチェックを実行します" 
  lane :ci_build_check do
    gym(
      scheme: "FadeMemo",
      configuration: "Debug",
      skip_archive: true
    )

    UI.success("✅ ビルドチェックが正常に完了しました！")
  end
end

after_all do |lane|
  sh "rm -f README.md" 
end